/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

public class App {
    public static void main(String[] args) {
        Disciplina matematica = new Disciplina();

        matematica.setCreditos(10);
        IO.println(matematica.getCreditos());
    }
}
