/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

import java.util.ArrayList;

public class App {

    private ArrayList<Conta> contas = new ArrayList<>();

    public void menu(int opcao){
        switch (opcao) {
            case 1:
                String n = IO.readln("Entre com o nome: ");
                double s = Double.parseDouble(IO.readln("Entre com o saldo inicial: "));
                long num = Long.parseLong(IO.readln("Entre com número da conta: "));
                Conta user = new Conta(num, s, n);
                contas.add(user);
                break;
            case 2:
                contas.forEach(IO::println);
                break;
            case 3:
                break;
            case 4:
                break;
    
            default:
                break;
        }
    }

    public static void main(String[] args) {
        // Menu com 3 opções 
        // 1 - Criar conta
        // 2 - Listar todas as contas
        // 3 - Sacar
        // 4 - Depositar
        // 5 - Sair
        App app = new App();
        System.out.println();

        app.menu();

        System.out.println("1 - Criar conta");
        System.out.println("2 - Listar todas as contas");
        System.out.println("3 - Sacar");
        System.out.println("4 - Depositar");
        System.out.println("5 - Sair");

        int opcao = Integer.parseInt(IO.readln("O que deseja fazer?"));
        
        while (opcao != 5) {
            app.menu(opcao);
        }
        
    }
}
