/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

public class App {
    public static void main(String[] args) {
        Robo r = new Robo("aa");
        Robo m = new Robo("bb");
        Robo n = new Robo("cc");

        IO.print(r);
    }
}
